name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        sudo apt install gdb
        cargo test --verbose
        cargo test test_core_safe_func --verbose -- --ignored
        cargo test test_core_canary --verbose -- --ignored
    - name: Code Style
      run: cargo fmt -- --check
